# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T14:54:01+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity

from models import (
    SscerCertificatePostRequest,
    SscerCertificatePostResponse,
    SscerCertificatePostResponse1,
    SscerCertificatePostResponse2,
    SscerCertificatePostResponse3,
    SscerCertificatePostResponse4,
    SscerCertificatePostResponse5,
    SscerCertificatePostResponse6,
    SvcerCertificatePostRequest,
    SvcerCertificatePostResponse,
    SvcerCertificatePostResponse1,
    SvcerCertificatePostResponse2,
    SvcerCertificatePostResponse3,
    SvcerCertificatePostResponse4,
    SvcerCertificatePostResponse5,
    SvcerCertificatePostResponse6,
)

app = MCPProxy(
    description='Bihar School Examination Board, Patna (http://biharboardonline.bihar.gov.in) has made available Class X (2018) marksheets and provisional certificates, which can be pulled by students into their accounts.',
    termsOfService='https://apisetu.gov.in/terms.php',
    title='Bihar State Board of School Examination, Bihar',
    version='3.0.0',
    servers=[{'url': 'https://apisetu.gov.in/biharboard/v3'}],
)


@app.post(
    '/sscer/certificate',
    description=""" API to verify Class X Marksheet. """,
    tags=['certificate_management'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def sscer(body: SscerCertificatePostRequest = None):
    """
    Class X Marksheet
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/svcer/certificate',
    description=""" API to verify Class X Provisional Certificate. """,
    tags=['certificate_management'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def svcer(body: SvcerCertificatePostRequest = None):
    """
    Class X Provisional Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
